apiVersion: v1
kind: Pod
metadata:
  name: download-pod
  namespace: ftschirpke
spec:
  containers:
  - name: download
    image: friedricht/wow-download
    command:
      - /bin/sh
      - "-c"
      - "sleep infinity"
    workingDir: /nfs
    volumeMounts:
      - mountPath: /nfs
        name: nfs
    securityContext:
      runAsUser: 0
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nf-input
  securityContext:
    runAsUser: 0
